# Generated by Django 5.0.3 on 2024-03-18 23:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_webgis', '0002_regiaoadministrativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loteexistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=31983)),
                ('ct_ciu', models.CharField(blank=True, max_length=12, null=True)),
                ('lt_enderec', models.CharField(blank=True, max_length=115, null=True)),
                ('lt_cep', models.CharField(blank=True, max_length=8, null=True)),
                ('lt_setor', models.CharField(blank=True, max_length=70, null=True)),
                ('lt_quadra', models.CharField(blank=True, max_length=50, null=True)),
                ('lt_conjunt', models.CharField(blank=True, max_length=35, null=True)),
                ('lt_nome', models.CharField(blank=True, max_length=80, null=True)),
                ('lt_ra', models.IntegerField(blank=True, null=True)),
                ('ac_area_ct', models.FloatField(blank=True, null=True)),
                ('ct_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camadas.feature_polygon_lote_existente',
                'managed': False,
            },
        ),
    ]
